- name: Setup PostgreSQL Master
  hosts: db
  become: true
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/app.yml
  roles:
    - postgresql

- name: Setup PostgreSQL Replica
  hosts: app
  become: true
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
  vars_files:
    - ./inventories/group_vars/app.yml
  roles:
    - postgresql
  vars:
    postgresql_master_address: 192.168.56.202
    postgresql_replica_user:
      name: replica
      password: replica